apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-web
  template:
    metadata:
      labels:
        app: nfs-web
    spec:
      containers:
        - name: web
          image: nginx
          volumeMounts:
            - name: webdata
              mountPath: /usr/share/nginx/html
      volumes:
        - name: webdata
          persistentVolumeClaim:
            claimName: pvc-nfs
